### ISSUE TITLE
error with transpose in neural renderer

### ISSUE THREAD

**Issue by maartenjv** [akanazawa/human_dynamics#17]
Hello, I get the following error in the visualisation stage. Seems pretty basic, could this be a numpy version issue maybe.

running anaconda3 on windows 7 with numpy 1.13.3

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\human_dynamics\human_dynamics-master\demo_video.py", line 246, in <module>
    main(model_hmmr)
  File "D:\human_dynamics\human_dynamics-master\demo_video.py", line 234, in main
    run_on_video(model, config.vid_path, trim_length)
  File "D:\human_dynamics\human_dynamics-master\demo_video.py", line 216, in run_on_video
    trim_length=trim_length
  File "D:\human_dynamics\human_dynamics-master\demo_video.py", line 190, in predict_on_tracks
    trim_length=trim_length,
  File "D:\human_dynamics\human_dynamics-master\src\evaluation\run_video.py", line 161, in render_preds
    rotated_view=True,
  File "D:\human_dynamics\human_dynamics-master\src\util\render\nmr_renderer.py", line 416, in visualize_img_orig
    no_text=no_text,
  File "D:\human_dynamics\human_dynamics-master\src\util\render\nmr_renderer.py", line 306, in visualize_img
    rend_img = renderer(vert, cam=cam, img=input_img, color_name=mesh_color)
  File "D:\human_dynamics\human_dynamics-master\src\util\render\nmr_renderer.py", line 154, in __call__
    rend = rend.data.cpu().numpy().transpose((0, 2, 3, 1))
AttributeError: 'tuple' object has no attribute 'data'

**Comment by Zju-George** [comment]
That's strange, have you built neural renderer(run setup.py)?
@maartenjv

**Comment by maartenjv** [comment]
yes, I did run the setup. Although it gives some strange warnings and some code had to be adjusted to get it to work, as you know :)
https://github.com/daniilidis-group/neural_renderer/issues/47

But I can run the demos from neural rendering without errors...

**Comment by Zju-George** [comment]
Oh you are maartenjv!!
You can compare The error file with my fork's file, is there any different?
If not, I guess that's The package's version problem.
Next Monday I'll check all my package's version like numpy and tell you.


Best, 
George




 
---Original---

**Comment by maartenjv** [comment]
Looks like that part of the code is the same. So hopefully package version change will solve the probem.

**Comment by maartenjv** [comment]
I think I've solved the issue. 
in nmr_renderer.py line 152:
`rend = self.renderer.render(proj_verts, faces, texture)` returns: 
`return out['rgb'], out['depth'], out['alpha']` (renderer.py from the neural_renderer install)

So you have to do `rend = rend[0]` to make it work.

Not sure when this change was made to neural renderer, but it seems pretty recent?

**Comment by Zju-George** [comment]
Congratulations!


we can Keep contact cuz WE are all want to deep in hmmr!


 
---Original---
