### ISSUE TITLE
A problem in read_human36m.py

### ISSUE THREAD

**Issue by seamanj** [akanazawa/human_dynamics#40]
Dear author

when I tried to run read_human36m.py, it gives the following error. I have already set up the directories and CDF. Could u help with this issue? thanks in advance.

Regards

---------------------------------------------------------------------------------------------------------------

```
read_human36m.py:184: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for tr in child.getchildren():
read_human36m.py:185: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  if tr.getchildren()[0].text == str(myactionno):
read_human36m.py:186: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  if tr.getchildren()[1].text == str(trialno):
read_human36m.py:187: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  return tr.getchildren()[2 + sbj_id - 1].text
Sub: 1, action 1,  trial 1, cam 1
Orig seq_name Directions 1, new_seq_name Directions_0
Saving to /home/seamanj/Software/Dataset/human36m_25fps/S1/Directions_0/cam_0
Writing /home/seamanj/Software/Dataset/human36m_25fps/S1/Directions_0/cam_0/camera_wext.pkl
Traceback (most recent call last):
  File "read_human36m.py", line 466, in <module>
    main(raw_data_root, output_root, frame_skip)
  File "read_human36m.py", line 397, in main
    pose3d_paths[cam_id - 1], is_3d=True, joint_ids=joint_ids)
IndexError: list index out of range

```

**Comment by seamanj** [comment]
Sorry, it turns out the human3.6m dataset is broken.
