### ISSUE TITLE
List index out of range when run the demo

### ISSUE THREAD

**Issue by EnochChan97** [akanazawa/human_dynamics#45]
hi author! I'm sorry to bother you.

I run the `python -m demo_video --vid_path demo_data/penn_action-2278.mp4 --load_path models/hmmr_model.ckpt-1119816` on cuda9.0,torch0.4,and encountered an error :

WARNING:tensorflow:From /home/chensien/venv_hmmr/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v2.py:224: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-23 20:26:08.335596: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-23 20:26:08.715735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:03:00.0
totalMemory: 10.91GiB freeMemory: 7.90GiB
2019-12-23 20:26:09.091559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 1 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:05:00.0
totalMemory: 10.91GiB freeMemory: 2.18GiB
2019-12-23 20:26:09.091729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1
2019-12-23 20:26:10.527439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-23 20:26:10.527511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1
2019-12-23 20:26:10.527521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N Y
2019-12-23 20:26:10.527543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   Y N
2019-12-23 20:26:10.528594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6702 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2019-12-23 20:26:10.657091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 6703 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
2019-12-23 20:26:10.660406: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 6.55G (7029050368 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.662843: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 5.89G (6326145024 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.665144: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 5.30G (5693530624 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.667553: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 4.77G (5124177408 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.670259: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 4.29G (4611759616 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.674016: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 3.87G (4150583552 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.676184: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 3.48G (3735525120 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.678594: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 3.13G (3361972480 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.681124: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 2.82G (3025775104 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.683562: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 2.54G (2723197440 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-12-23 20:26:10.686430: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 2.28G (2450877696 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
Restoring resnet vars from models/hmr_noS5.ckpt-642561
INFO:tensorflow:Restoring parameters from models/hmr_noS5.ckpt-642561
Restoring checkpoint  models/hmmr_model.ckpt-1119816
INFO:tensorflow:Restoring parameters from models/hmmr_model.ckpt-1119816
Computing tracks on demo_data/penn_action-2278.mp4.
Writing frames to file: done!
Per-frame detection: done!
Tracking: done!
Not all frames have people detected in it.
Traceback (most recent call last):
  File "/home/chensien/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chensien/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chensien/human_dynamics/demo_video.py", line 250, in <module>
    main(model_hmmr)
  File "/home/chensien/human_dynamics/demo_video.py", line 238, in main
    run_on_video(model, config.vid_path, trim_length)
  File "/home/chensien/human_dynamics/demo_video.py", line 220, in run_on_video
    trim_length=trim_length
  File "/home/chensien/human_dynamics/demo_video.py", line 132, in predict_on_tracks
    all_kps = get_labels_poseflow(poseflow_path, len(im_paths))
  File "/home/chensien/human_dynamics/demo_video.py", line 87, in get_labels_poseflow
    if frame_ids[0] != 0:
IndexError: list index out of range

could you please give me a hand and solve this?thx!

**Comment by yan877554365** [comment]
抱歉我看不懂你的语音😂😂

**Comment by yan877554365** [comment]
我看不懂你的语言

**Comment by jasonyzhang** [comment]
Hi,

This looks like a problem with AlphaPose/PoseFlow not detecting any people in your video. Try uncommenting this line to visualize the PoseFlow predictions:
https://github.com/akanazawa/human_dynamics/blob/2f1791ef6498d3c58159763a08662cbdda4dee93/extract_tracks.py#L109

Also, it looks like at least one of your GPUs is running out of memory. You may want to try reducing the batch size or specifying CUDA_VISIBLE_DEVICES.

Best,
Jason

**Comment by EnochChan97** [comment]
> Hi,
> 
> This looks like a problem with AlphaPose/PoseFlow not detecting any people in your video. Try uncommenting this line to visualize the PoseFlow predictions:
> https://github.com/akanazawa/human_dynamics/blob/2f1791ef6498d3c58159763a08662cbdda4dee93/extract_tracks.py#L109
> 
> Also, it looks like at least one of your GPUs is running out of memory. You may want to try reducing the batch size or specifying CUDA_VISIBLE_DEVICES.
> 
> Best,
> Jason

Hi,It works!thanks a lot!
