### ISSUE TITLE
MemoryError sometimes when there are more than 1 people in the video

### ISSUE THREAD

**Issue by tcboy88** [akanazawa/human_dynamics#6]
MemoryError sometimes when there are more than 1 people, error as below
Also, I used --track_id 1 hoping to get only the largest tracked human but it is frequently not, anyway to choose only the largest or the most confident human?

Start loading json file...

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:16<00:00,  3.12it/s]
Start pose tracking...

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [04:09<00:00,  5.09s/it]
This video contains 27 people.
Export tracking results to json...

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 126258.40it/s]
PoseFlow successfully ran!
----------
Total number of PoseFlow tracks: 19
Processing track_id: 1
----------
Preprocessing frames.
----------
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yeo/Desktop/venv_hmmr/human_dynamics-master/demo_video.py", line 246, in <module>
    main(model_hmmr)
  File "/home/yeo/Desktop/venv_hmmr/human_dynamics-master/demo_video.py", line 232, in main
    run_on_video(model, vid_path, trim_length)
  File "/home/yeo/Desktop/venv_hmmr/human_dynamics-master/demo_video.py", line 216, in run_on_video
    trim_length=trim_length
  File "/home/yeo/Desktop/venv_hmmr/human_dynamics-master/demo_video.py", line 150, in predict_on_tracks
    bbox_param=bbox_params_smooth[i],
  File "/home/yeo/Desktop/venv_hmmr/human_dynamics-master/src/evaluation/run_video.py", line 81, in process_image
    mode='edge'
  File "/home/yeo/Desktop/venv_hmmr/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 1381, in pad
    newmat = _prepend_edge(newmat, pad_before, axis)
  File "/home/yeo/Desktop/venv_hmmr/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 175, in _prepend_edge
    axis=axis)
MemoryError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by jasonyzhang** [comment]
Longest track should be track_id 0.
If you are running out of ram, try lowering your video resolution first.
