### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by nayariml** [akanazawa/human_dynamics#70]
Hi, can someone help me, please?

I'm try to run the code and I stopped here src/render/nmr_render.py but I got this issues:

line 154: rend = rend.data.cpu().numpy().transpose((0, 2, 3, 1))
AttributeError: 'tuple' object has no attribute 'data'

I also printed the shape of this turple: 

torch.Size([1, 3, 244, 244])
torch.Size([1, 244, 244])
torch.Size([1, 244, 244])

I've tried a lot of ways to solve this, but I got other issues.. :|

it happened to extract hmmr_output files.
----------
Rendering results to demo_output/y3_1_1/hmmr_output.
----------
 0%|                                                                                                                     | 0/108 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo_video.py", line 247, in <module>
    main(model_hmmr)
  File "demo_video.py", line 235, in main
    run_on_video(model, config.vid_path, trim_length)
  File "demo_video.py", line 217, in run_on_video
    trim_length=trim_length
  File "demo_video.py", line 191, in predict_on_tracks
    trim_length=trim_length,
  File "/home/nayari/human_dynamics/src/evaluation/run_video.py", line 161, in render_preds
    rotated_view=True,
  File "/home/nayari/human_dynamics/src/util/render/nmr_renderer.py", line 432, in visualize_img_orig
    no_text=no_text,
  File "/home/nayari/human_dynamics/src/util/render/nmr_renderer.py", line 322, in visualize_img
    rend_img = renderer(vert, cam=cam, img=input_img, color_name=mesh_color)
  File "/home/nayari/human_dynamics/src/util/render/nmr_renderer.py", line 154, in __call__
    rend = rend.data.cpu().numpy().transpose((0, 2, 3, 1))
AttributeError: 'tuple' object has no attribute 'data'

**Comment by jasonyzhang** [comment]
Hi,

There was a slight API change in the newer versions of NMR. Try adding `rend = rend[0]` (the first element in the tuple should be the rendering that we want).

Best,
Jason

**Comment by nayariml** [comment]
Works!

Thanks for the quick reply and for this project.
I've changed the code to works with Tensorflow 2.x. Everything works fine now. Later I update the branch.

:)
